Write access is no longer required and other fixes
* Write access to music directory no longer required as all cache files
  are now stored in ~/.aletheia-mobile/locked, ~/.aletheia-mobile/art,
  and ~/.aletheia-mobile/loops. Move them over from your music and sound
  directories, if needed.
* Import download buttons now search in subdirectories
* Renaming and archiving button options now require READ_ONLY=false in
  ~/.aletheia-mobile/config
* Removes internal files in ~/.aletheia-mobile on quit
* Now handles SIGTERM, SIGHUP, and SIGQUIT signals
* RPM and DEB build scripts clean up the tmp directory
* Play button now stays consistent through song change

diff --git a/create_deb b/create_deb
--- a/create_deb
+++ b/create_deb
@@ -28,7 +28,7 @@ fi
 
 NAME="aletheia-mobile"
 VERSION=3
-REVISION=3
+REVISION=4
 SRCDIR=${SRCDIR:-"$(pwd)"}
 TMPDIR="/tmp/${NAME}_${VERSION}-${REVISION}_all"
 
@@ -63,14 +63,20 @@ install -m 644 "$SRCDIR/LICENSE" "$TMPDIR/usr/share/doc/$NAME/"
 
 sed -i "/^ALETHEIA_DATA_DIR/s#.*#ALETHEIA_DATA_DIR=\"/usr/share/$NAME/\"#g" "$TMPDIR/usr/bin/$NAME"
 
-cd "$TMPDIR" || exit 1
+if ! cd "$TMPDIR"; then
+	echo -e "\n${RED}Error: ${NOCOLOR}Could not enter $TMPDIR.\n"
+	exit 1
+fi
 chown -R root:root "$TMPDIR"
 dpkg-deb --build "$TMPDIR"
 if [ -e "/tmp/${NAME}_${VERSION}-${REVISION}_all.deb" ]; then
 	echo -e "\n${GREEN}Install:\n\n${NOCOLOR}sudo apt install /tmp/${NAME}_${VERSION}-${REVISION}_all.deb\n"
 else
-	echo -e "\n${RED}Error:$NOCOLOR Package creation failed\n"
+	echo -e "\n${RED}Error: ${NOCOLOR}Package creation failed\n"
+	rm -rf "$TMPDIR"
 	exit 1
 fi
+
+rm -rf "$TMPDIR"
 
 exit 0
diff --git a/create_rpm b/create_rpm
--- a/create_rpm
+++ b/create_rpm
@@ -28,7 +28,7 @@ fi
 
 NAME="aletheia-mobile"
 VERSION=3
-REVISION=3
+REVISION=4
 SRCDIR=${SRCDIR:-"$(pwd)"}
 TMPDIR="/tmp/rpm-package-$NAME/"
 
@@ -69,10 +69,14 @@ fi
 
 rm -f "$path/RPMS/noarch/${NAME}-${VERSION}-"*".noarch.rpm" >/dev/null 2>&1
 
-cd "$TMPDIR" || exit 1
+if ! cd "$TMPDIR"; then
+	echo -e "\n${RED}Error: ${NOCOLOR}Could not enter $TMPDIR.\n"
+	exit 1
+fi
 
 if ! rpmbuild -bb rpmbuild/SPECS/"$NAME".spec; then
 	echo -e "\n${RED}Error: ${NOCOLOR}Package creation failed\n"
+	rm -rf "$TMPDIR"
 	exit 1
 fi
 
@@ -84,5 +88,7 @@ if [[ "$OS" == *"openSUSE"* ]]; then
 else
 	echo -e "\n${GREEN}Install:\n\n${NOCOLOR}sudo dnf install ./${file##*/}\n"
 fi
+
+rm -rf "$TMPDIR"
 
 exit 0
